# Generated by Django 5.0.6 on 2025-01-24 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'student'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
