# Generated by Django 5.0.6 on 2025-01-22 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_pdf_file_course_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
